# Generated by Django 4.2.20 on 2025-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("viewed", "viewed"),
                    ("liked", "liked"),
                    ("hated", "hated"),
                    ("followed", "followed"),
                    ("blocked", "blocked"),
                ],
                max_length=20,
            ),
        ),
    ]
