# Generated by Django 4.2.20 on 2025-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0004_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("viewed", "viewed"),
                    ("liked", "liked"),
                    ("disliked", "disliked"),
                    ("followed", "followed"),
                    ("loved", "loved"),
                ],
                max_length=20,
            ),
        ),
    ]
